services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/taskorganizer?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2
    networks:
      - task-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: taskorganizer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - task-network

networks:
  task-network:
